FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
MAINTAINER Salzburg Research <nimble-srfg@salzburgresearch.at>

# add configuration
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml