spring_profiles: postgresql

database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://uaa-db:5432/${DB_ENV_DB:postgres}
  username: ${DB_ENV_USER:postgres}
  password: ${DB_ENV_PASS:}

oauth:
  client:
    override: true
    autoapprove:
      - cloudbreak_shell
      - periscope-client
  clients:
    sultans:
      id: sultans
      secret: sultanssecret
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write
      authorities: uaa.resource,scim.write,scim.read,password.write,uaa.admin,clients.read,clients.admin, aczones.uaa.admin,openid
    uluwatu:
      id: uluwatu
      secret: uluwatusecret
      authorized-grant-types: authorization_code,client_credentials
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,openid,password.write,cloudbreak.events,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,periscope.cluster,cloudbreak.recipes
      authorities: cloudbreak.subscribe
      redirect-uri: http://localhost:3000/authorize
    cloudbreak:
      id: cloudbreak
      secret: cloudbreaksecret
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write
      authorities: uaa.resource,scim.read,scim.write,password.write
    cloudbreak_shell:
      id: cloudbreak_shell
      authorized-grant-types: implicit
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,openid,password.write,cloudbreak.recipes
      authorities: uaa.none
      redirect-uri: http://cloudbreak.shell
    periscope-client:
      id: periscope-client
      authorized-grant-types: implicit
      scope: cloudbreak.stacks,openid,periscope.cluster
      authorities: uaa.none
      redirect-uri: http://periscope.client
    periscope:
      id: periscope
      secret: periscopesecret
      authorized-grant-types: client_credentials
      scope: none
      authorities: cloudbreak.autoscale,uaa.resource,scim.read

scim:
  users:
    #FORMAT: username|password|email|first_name|last_name(|comma-separated-authorities)
    - j.innerbichler@gmail.com|12345|j.innerbichler@gmail.com|Johannes|Innerbichler|uaa.admin,clients.read,clients.write,clients.secret

# uaac client add admin --name Admin --authorized_grant_types client_credentials --scope scim.read,scim.write,password.write --authorities uaa.resource,scim.write,scim.read,password.write,uaa.admin,clients.read,clients.admin,aczones.uaa.admin