CREATE DATABASE identitydb WITH OWNER admin;
CREATE DATABASE catalogcategorydb WITH OWNER admin;
CREATE DATABASE camundadb WITH OWNER admin;
CREATE DATABASE businessprocessdb WITH OWNER admin;
CREATE DATABASE ubldb WITH OWNER admin;
CREATE DATABASE modalmldb WITH OWNER admin;
CREATE DATABASE catalogsyncdb WITH OWNER admin;
CREATE DATABASE marmottadb WITH OWNER admin;
CREATE DATABASE datachanneldb WITH OWNER admin;