FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.3
MAINTAINER Salzburg Research <nimble-srfg@salzburgresearch.at>

# add configuration
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml